const destinations=[{name:"Bariloche",country:"Argentina",image:"https://images.unsplash.com/photo-1605540436563-5bca919ae766?auto=format&fit=crop&w=900&q=80",price:420000,days:7,style:"equilibrado",temp:"3–12 °C",best:"Nieve y lagos",desc:"Montañas, chocolate, lagos y escapadas con paisajes espectaculares.",truth:"Es hermoso, pero en temporada alta conviene reservar alojamiento y excursiones con anticipación."},{name:"Río de Janeiro",country:"Brasil",image:"https://images.unsplash.com/photo-1483729558449-99ef09a8c325?auto=format&fit=crop&w=900&q=80",price:590000,days:7,style:"equilibrado",temp:"22–29 °C",best:"Playa y ciudad",desc:"Playas famosas, miradores, samba y una ciudad con muchísima energía.",truth:"La mejor experiencia combina playa de día, zonas concurridas de noche y traslados bien planificados."},{name:"Madrid",country:"España",image:"https://images.unsplash.com/photo-1539037116277-4db20889f2d4?auto=format&fit=crop&w=900&q=80",price:1450000,days:10,style:"confort",temp:"10–22 °C",best:"Cultura y gastronomía",desc:"Museos, barrios caminables, tapas y excelentes conexiones con Europa.",truth:"Es fácil de recorrer, pero comer y alojarse en el centro puede elevar bastante el presupuesto."},{name:"Tokio",country:"Japón",image:"https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=900&q=80",price:2300000,days:12,style:"confort",temp:"14–24 °C",best:"Tecnología y cultura",desc:"Una mezcla impresionante de tradición, tecnología, orden y gastronomía.",truth:"El transporte funciona muy bien, aunque las estaciones grandes pueden resultar confusas al principio."},{name:"Lima",country:"Perú",image:"https://images.unsplash.com/photo-1531968455001-5c5272a41129?auto=format&fit=crop&w=900&q=80",price:520000,days:5,style:"economico",temp:"15–21 °C",best:"Gastronomía",desc:"Una capital costera ideal para comer increíble y conectar con otros destinos del Perú.",truth:"Miraflores y Barranco son muy prácticos para una primera visita; el tránsito puede demorar bastante."},{name:"Santiago de Chile",country:"Chile",image:"https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?auto=format&fit=crop&w=900&q=80",price:360000,days:4,style:"economico",temp:"7–20 °C",best:"Escapada urbana",desc:"Una ciudad moderna, rodeada por montañas y perfecta para una escapada corta.",truth:"Se disfruta mucho con pocos días; revisá la calidad del aire y el clima antes de subir a miradores."}];
const $=s=>document.querySelector(s),cards=$("#destinationCards"),modal=$("#destinationModal");let visible=[...destinations].slice(0,3);
function money(n){return new Intl.NumberFormat("es-AR",{style:"currency",currency:"ARS",maximumFractionDigits:0}).format(n)}
function toast(text){const t=$("#toast");t.textContent=text;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2600)}
function renderCards(items){cards.innerHTML=items.map(d=>`<button class="destination-card" style="background-image:url('${d.image}')" data-name="${d.name}"><div class="content"><small>${d.country}</small><h3>${d.name}</h3><p>${d.best}</p><span class="price">Desde ${money(d.price)}</span></div></button>`).join("");document.querySelectorAll(".destination-card").forEach(btn=>btn.addEventListener("click",()=>openDestination(btn.dataset.name)))}
function openDestination(name){const d=destinations.find(x=>x.name.toLowerCase()===name.toLowerCase())||destinations.find(x=>x.name.toLowerCase().includes(name.toLowerCase()));if(!d){toast("Todavía no cargamos ese destino. Probá con otro.");return}$("#modalImage").src=d.image;$("#modalImage").alt=d.name;$("#modalCountry").textContent=d.country;$("#modalTitle").textContent=d.name;$("#modalDescription").textContent=d.desc;$("#modalTruth").textContent=d.truth;$("#modalFacts").innerHTML=`<div><small>Presupuesto</small><strong>${money(d.price)}</strong></div><div><small>Ideal</small><strong>${d.days} días</strong></div><div><small>Clima</small><strong>${d.temp}</strong></div>`;modal.showModal()}
renderCards(visible);$("#shuffleBtn").addEventListener("click",()=>{visible=[...destinations].sort(()=>Math.random()-.5).slice(0,3);renderCards(visible)});$("#closeModal").addEventListener("click",()=>modal.close());$("#searchForm").addEventListener("submit",e=>{e.preventDefault();openDestination($("#destinationInput").value.trim())});$("#buildTripBtn").addEventListener("click",()=>{modal.close();toast("Itinerario base creado. Esta función será Premium.")});document.querySelectorAll("[data-scroll]").forEach(b=>b.addEventListener("click",()=>document.getElementById(b.dataset.scroll)?.scrollIntoView({behavior:"smooth"})));
$("#flightAlertForm").addEventListener("submit",e=>{e.preventDefault();const origin=$("#origin").value,dest=$("#flightDestination").value,budget=Number($("#maxBudget").value),result=$("#alertResult");result.classList.remove("hidden");result.innerHTML=`<strong>Alerta creada</strong><br>Te avisaremos cuando aparezca una opción desde <b>${origin}</b> hacia <b>${dest}</b> por menos de <b>${money(budget)}</b>.`;localStorage.setItem("nexoAlert",JSON.stringify({origin,dest,budget,flex:$("#dateFlex").value}))});
$("#budgetForm").addEventListener("submit",e=>{e.preventDefault();const budget=Number($("#tripBudget").value),style=$("#travelStyle").value;let matches=destinations.filter(d=>d.price<=budget*1.08&&(style==="equilibrado"||d.style===style||d.price<=budget*.8));matches=matches.sort((a,b)=>a.price-b.price).slice(0,3);$("#budgetResults").innerHTML=matches.length?matches.map(d=>`<button class="mini-card" data-name="${d.name}"><strong>${d.name}</strong><span>${d.country}</span><p>${d.days} días · ${money(d.price)}</p></button>`).join(""):`<div class="result-box">Con ese presupuesto no encontramos una opción cargada. Probá aumentando el monto o reduciendo días.</div>`;document.querySelectorAll(".mini-card").forEach(b=>b.addEventListener("click",()=>openDestination(b.dataset.name)))});
$("#airportToggle").addEventListener("change",e=>{$("#airportContent").classList.toggle("disabled",!e.target.checked);toast(e.target.checked?"Modo aeropuerto activado":"Modo aeropuerto desactivado")});$("#notifyFlightBtn").addEventListener("click",()=>toast("Avisos del vuelo activados"));$("#premiumBtn").addEventListener("click",()=>toast("Premium con API oficial estará disponible cuando conectemos el servidor"));$("#profileBtn").addEventListener("click",()=>toast("Perfil de Walter: Buenos Aires · Preferencias guardadas"));
const saved=localStorage.getItem("nexoAlert");if(saved){try{const a=JSON.parse(saved);$("#origin").value=a.origin;$("#flightDestination").value=a.dest;$("#maxBudget").value=a.budget;const r=$("#alertResult");r.classList.remove("hidden");r.innerHTML=`<strong>Alerta activa</strong><br>${a.origin} → ${a.dest}, hasta ${money(a.budget)}.`}catch{}}
let trackedFlight="";
function normalizeFlight(value){return value.toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,10)}
function fr24Url(flight){return `https://www.flightradar24.com/data/flights/${encodeURIComponent(flight.toLowerCase())}`}
function openTrackedFlight(){if(!trackedFlight){toast("Primero ingresá un número de vuelo");return}window.open(fr24Url(trackedFlight),"_blank","noopener,noreferrer")}
$("#flightTrackerForm").addEventListener("submit",e=>{e.preventDefault();trackedFlight=normalizeFlight($("#trackerFlight").value);if(trackedFlight.length<3){toast("Ingresá un número de vuelo válido");return}$("#trackerFlight").value=trackedFlight;$("#trackedFlight").textContent=trackedFlight;$("#trackerResult").classList.remove("hidden");localStorage.setItem("nexoTrackedFlight",trackedFlight);openTrackedFlight()});
$("#openFr24Btn").addEventListener("click",openTrackedFlight);
const savedFlight=normalizeFlight(localStorage.getItem("nexoTrackedFlight")||"");if(savedFlight){trackedFlight=savedFlight;$("#trackerFlight").value=savedFlight;$("#trackedFlight").textContent=savedFlight;$("#trackerResult").classList.remove("hidden")}
if("serviceWorker" in navigator)navigator.serviceWorker.register("service-worker.js").catch(()=>{});